### PR TITLE
fixed runcmd typo

### PR DESCRIPTION
**Pull request by marianalevineu**
Fixed Exercise_3/array-job/submit_array_slurm.bash  line: runcmd="./example_array 5"

### CODE REVIEW

**Comment by Prasanth-Dwadasi** [comment]
looks good , now working

**Review by Prasanth-Dwadasi — COMMENTED** [review]
looks good now working

**Comment by dhml** [comment]
@Prasanth-Dwadasi, if this change set looks good and is working as expected I think you want to merge this PR instead of closing it.  I'm re-opening this PR so you can confirm.

**Comment by marianalevineu** [comment]
thanks @dhml  I think he closed it by mistake without approving it

**Review by Prasanth-Dwadasi — APPROVED** [review]
working now

**Comment by marianalevineu** [comment]
thanks @Prasanth-Dwadasi !

**Comment by dhml** [comment]
@Prasanth-Dwadasi, @marianalevineu, understood.  Please keep in mind that our convention is for the PR author (i.e. @marianalevineu in this case) to perform the merge once the PR has been fully approved.

**Pull request merged**
